[package]
name = "axum-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
axum = "0.7.5"
httpc-test = "0.1.10"
serde = "1.0.210"
serde_json = "1.0.128"

[dev-dependencies]
anyhow = "1.0.44"
httpc-test = "0.1.10"
 