/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare function saveFile(filePath: string, content: string): void
export declare function csvToExcel(filePath: string, fileContent: string): void
